/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas3;

/**
 *
 * @author USER
 */
public class tugas3 extends javax.swing.JFrame {
    String jns = "";
    int jml;
  
    /**
     * Creates new form tugas3
     */
    public tugas3() {
        initComponents();
        getJumlah();
        setjenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bill3.setVisible(false);
        bill4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        bill1.setVisible(false);
        bill2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        bill4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bill1 = new javax.swing.JLabel();
        bill2 = new javax.swing.JLabel();
        bill3 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        pilihanbil = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        thasil = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Program Aritmatika");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 220, 50);

        jenis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel1.add(jenis);
        jenis.setBounds(320, 70, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 70, 110, 14);

        panel.setBackground(new java.awt.Color(255, 204, 204));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(null);

        bill4.setText("Bilangan 4");
        panel.add(bill4);
        bill4.setBounds(20, 230, 90, 14);

        jLabel4.setText("Jumlah Bilangan");
        panel.add(jLabel4);
        jLabel4.setBounds(10, 40, 100, 14);

        bill1.setText("Bilangan 1");
        panel.add(bill1);
        bill1.setBounds(20, 90, 90, 14);

        bill2.setText("Bilangan 2");
        panel.add(bill2);
        bill2.setBounds(20, 140, 90, 14);

        bill3.setText("Bilangan 3");
        panel.add(bill3);
        bill3.setBounds(20, 180, 90, 14);
        panel.add(b1);
        b1.setBounds(130, 80, 210, 30);
        panel.add(b2);
        b2.setBounds(130, 130, 210, 30);
        panel.add(b3);
        b3.setBounds(130, 170, 210, 30);
        panel.add(b4);
        b4.setBounds(130, 220, 210, 30);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(160, 50, 120, 20);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(170, 260, 110, 30);
        panel.add(thasil);
        thasil.setBounds(120, 310, 220, 80);
        panel.add(ket);
        ket.setBounds(160, 10, 110, 30);

        jPanel1.add(panel);
        panel.setBounds(40, 100, 440, 410);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 520);

        setSize(new java.awt.Dimension(525, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        
        if (jenis.equals("Penjumlahan")) {
            if(jml == 2) {
                hsl =  a1 + a2;
                thasil.setText(""+a1+" + " + a2 + " = "+hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 + a2 + a3;
                thasil.setText(""+a1 + " + " + a2+ " + " + a3 + " = " + hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1 + " + " + a2+ " + " + a3 + " + " + a4+ " = " + hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1 - a2;
                thasil.setText(""+a1 + " - "+ a2+ " = "+ hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 - a2 - a3;
                thasil.setText(""+a1 + " - "+ a2+ " - " + a3 +" = "+ hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                thasil.setText(""+a1 + " - "+ a2+ " - " + a3 + " - " + a4 +"= "+ hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1 * a2;
                thasil.setText(""+a1 + " * "+ a2+ " = "+ hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 * a2 * a3;
                thasil.setText(""+a1 + " * "+ a2+ " * " + a3 +" = "+ hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                thasil.setText(""+a1 + " * "+ a2+ " * " + a3 + " * " + a4 +" = "+ hsl);
            }
        }
        else if(jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1 / a2;
                thasil.setText(""+a1 + " / "+ a2+ " = "+ hsl);
            }
            if(jml == 3){
                a3 = Double.parseDouble(b3.getText().toString());
                hsl = a1 / a2 / a3;
                thasil.setText(""+a1 + " / "+ a2+ " / " + a3 +" = "+ hsl);
            }
            if(jml == 4){
                a3 = Double.parseDouble(b3.getText().toString());
                a4 = Double.parseDouble(b4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                thasil.setText(""+a1 + " / "+ a2+ " / " + a3 + " / " + a4 +" = "+ hsl);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
     setjenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
      getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed
    public void getJumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
            bill3.setVisible(false);
            bill4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bill1.setVisible(true);
            bill2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 2;
        }
       else if(pilihanbil.getSelectedItem().equals("3")){
            bill3.setVisible(true);
            bill4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            bill1.setVisible(true);
            bill2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 3;
       }else if(pilihanbil.getSelectedItem().equals("4")){
            bill3.setVisible(true);
            bill4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            bill1.setVisible(true);
            bill2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 4;
       }
    }
    public void setjenis() {
       if(jenis.getSelectedItem().equals("Penjumlahan")){
           jns = "Penjumlahan";
           ket.setText("Penjumlahan");
           panel.setVisible(true);
           pilihanbil.setEnabled(true);
       }
       else if(jenis.getSelectedItem().equals("Pengurangan")){
           jns = "Pengurangan";
           ket.setText("Pengurangan");
           panel.setVisible(true);
           pilihanbil.setEnabled(true);
       }
       else if(jenis.getSelectedItem().equals("Perkalian")){
           jns = "Perkalian";
           ket.setText("Perkalian");
           panel.setVisible(true);
           pilihanbil.setEnabled(true);
       }
       else if(jenis.getSelectedItem().equals("Pembagian")){
           jns = "Pembagian";
           ket.setText("Pembagian");
           panel.setVisible(true);
           pilihanbil.setEnabled(true);
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bill1;
    private javax.swing.JLabel bill2;
    private javax.swing.JLabel bill3;
    private javax.swing.JLabel bill4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables

}
