
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class penarikan extends javax.swing.JFrame {

    /**
     * Creates new form penarikan
     */
    public penarikan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tarikan = new javax.swing.JTextField();
        jButtonok = new javax.swing.JButton();
        jButtonmenu = new javax.swing.JButton();
        jButtonkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Masukkan Nominal Tarik Tunai");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 220, 50);
        getContentPane().add(tarikan);
        tarikan.setBounds(60, 70, 140, 30);

        jButtonok.setText("ok");
        jButtonok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonokActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonok);
        jButtonok.setBounds(250, 70, 80, 23);

        jButtonmenu.setText("Menu");
        jButtonmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonmenu);
        jButtonmenu.setBounds(70, 130, 73, 23);

        jButtonkeluar.setText("exit");
        jButtonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonkeluar);
        jButtonkeluar.setBounds(220, 130, 51, 23);

        setSize(new java.awt.Dimension(417, 219));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonokActionPerformed
         String tarik = tarikan.getText().toString();
        int Saldo = 5000000;
        int jumlah = Integer.parseInt(tarik);
        int sisa = Saldo - jumlah;
        
          if(jumlah>Saldo)
           JOptionPane.showMessageDialog(null,"Saldo anda tidak cukup!!","Transaksi gagal",0);
       
       else{
           Saldo = Saldo - jumlah;
           JOptionPane.showMessageDialog(null,"Saldo anda saat ini : "+sisa);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonokActionPerformed

    private void jButtonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonkeluarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonkeluarActionPerformed

    private void jButtonmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmenuActionPerformed
        new pilihantransaksi().setVisible(true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penarikan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonkeluar;
    private javax.swing.JButton jButtonmenu;
    private javax.swing.JButton jButtonok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tarikan;
    // End of variables declaration//GEN-END:variables
}
